# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewscontroller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dayOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('content', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
