# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewscontroller', '0003_auto_20170611_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayone',
            name='content',
        ),
        migrations.AddField(
            model_name='dayone',
            name='setone',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayone',
            name='settwo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dayone',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
