# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewscontroller', '0004_auto_20170611_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayone',
            name='exercisetime',
            field=models.FloatField(default=30),
            preserve_default=False,
        ),
    ]
