# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewscontroller', '0005_dayone_exercisetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayone',
            name='imagelink',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
