# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewscontroller', '0006_dayone_imagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='dayTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('setone', models.CharField(max_length=500)),
                ('settwo', models.CharField(max_length=500, null=True)),
                ('exercisetime', models.FloatField()),
                ('imagelink', models.CharField(max_length=500)),
            ],
        ),
    ]
