# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewscontroller', '0009_dayfive_dayfour_daysix'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayfive',
            name='settthree',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dayfour',
            name='settthree',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='daysix',
            name='settthree',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='daythree',
            name='setthree',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
