# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewscontroller', '0012_shareyourweight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dayFive',
        ),
        migrations.DeleteModel(
            name='dayFour',
        ),
        migrations.DeleteModel(
            name='dayOne',
        ),
        migrations.DeleteModel(
            name='daySix',
        ),
        migrations.DeleteModel(
            name='dayThree',
        ),
        migrations.DeleteModel(
            name='dayTwo',
        ),
        migrations.DeleteModel(
            name='music',
        ),
        migrations.DeleteModel(
            name='shareYourWeight',
        ),
    ]
