# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_uatstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerstatus',
            name='timestamp',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uatstatus',
            name='timestamp',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
