# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20181125_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='testerstatus',
            name='timestamp',
            field=models.DateTimeField(default=b'2018-11-25 19:45[:13[.040000]]'),
        ),
        migrations.AlterField(
            model_name='uatstatus',
            name='timestamp',
            field=models.DateTimeField(default=b'2018-11-25 19:45[:13[.040000]]'),
        ),
    ]
