# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20181125_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testerstatus',
            name='timestamp',
            field=models.DateTimeField(default=b'2018-11-25 20:22:36.721000'),
        ),
        migrations.AlterField(
            model_name='uatstatus',
            name='timestamp',
            field=models.DateTimeField(default=b'2018-11-25 20:22:36.722000'),
        ),
    ]
